[package]
name = "linkpad-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

description = "Cross-platform system proxy management for Linkpad"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Networking_WinInet"] }
